### ISSUE TITLE
사용자 도구 추가

### ISSUE THREAD

**Issue by jeongjo13** [LubizStudio/dreamseed#2]
최근 변경이나 최근 토론 등에서 사용자명을 누르면 the seed에서는 '기여내역' 버튼과 '사용자 문서' 버튼, 그리고 '차단' 버튼이 나옵니다. 이걸 dreamseed에서도 구현하면 좋을 것 같습니다.

![image](https://github.com/LubizStudio/dreamseed/assets/93975773/9e4d67ef-249c-4903-b127-5c2c82f3507e)

**Comment by jeongjo13** [comment]
![image](https://github.com/LubizStudio/dreamseed/assets/93975773/c77aa44c-2350-4b63-8f4d-56d1111ead8a)

**Comment by Jingzzinbbang** [comment]
될지는 모르겠지만 시도해보겠습니다

**Comment by jeongjo13** [comment]
인터페이스를 완전히 똑같이 하는 게 어렵다면 아래와 같은 방법도 고려 부탁드립니다.

- 기여내역, 사용자 문서, 차단 버튼 창 (사진 참고)은 댓글 블라인드/원문 보기 창 인터페이스 그대로 가져옵니다.
- 빠른 ACLGroup 창(추가할 그룹, 기간 등을 선택하는 창)은 창으로 만들기 어렵다면 새로운 페이지로라도 만들어지면 좋겠습니다.

**Comment by jeongjo13** [comment]
긴급차단 시 자동 입력되는 차단 메모:

최근 편집이나 문서 역사에서 차단 시: **이름공간명:문서명 r0 긴급차단** (이름공간명의 경우, 문서 이름공간도 '문서:'로 표시됨)
토론 창에서 차단 시: **토론 (토론 주소) #발언번호 긴급차단** (토룬 주소의 경우, 사이트주소/thread/는 생략)
차단 내역에서 긴급차단 시: **undefined 긴급차단**
편집 요청 창에서 긴급차단 시: **편집 요청 (주소) 긴급차단** (편집 요청 주소의 경우, 사이트주소/edit_request/는 생략)

**Comment by Jingzzinbbang** [comment]
> 인터페이스를 완전히 똑같이 하는 게 어렵다면 아래와 같은 방법도 고려 부탁드립니다.
> 
> * 기여내역, 사용자 문서, 차단 버튼 창 (사진 참고)은 댓글 블라인드/원문 보기 창 인터페이스 그대로 가져옵니다.
> * 빠른 ACLGroup 창(추가할 그룹, 기간 등을 선택하는 창)은 창으로 만들기 어렵다면 새로운 페이지로라도 만들어지면 좋겠습니다.

코드를 쭉 살펴본 결과 스레드에서 코드 가져오는 방식은 무리가 있어 보입니다. 애초에 가져와도 다 갈아야 할 것으로 보입니다

**Comment by Jingzzinbbang** [comment]
> 긴급차단 시 자동 입력되는 차단 메모:
> 
> 최근 편집이나 문서 역사에서 차단 시: **이름공간명:문서명 r0 긴급차단** (이름공간명의 경우, 문서 이름공간도 '문서:'로 표시됨) 토론 창에서 차단 시: **토론 (토론 주소) #발언번호 긴급차단** (토룬 주소의 경우, 사이트주소/thread/는 생략) 차단 내역에서 긴급차단 시: **undefined 긴급차단** 편집 요청 창에서 긴급차단 시: **편집 요청 (주소) 긴급차단** (편집 요청 주소의 경우, 사이트주소/edit_request/는 생략)

해당 부분은 힘들 것 같아 바로 ACL Group 페이지로 넘어가는 형식으로만 하겠습니다.

**Comment by Jingzzinbbang** [comment]
the seed 방식은 힘들 것 같고 오픈나무 형식으로 페이지로 넘어가게는 시도 해보겠습니다

**Comment by jeongjo13** [comment]
확인했습니다.

**Comment by Jingzzinbbang** [comment]
해볼려고 했는데 제 코딩 실력 부족 + 코드가 너무 방대해서 오히려 엔진이 망가져 진행하지 않기로 했으며 양해바랍니다.
