### ISSUE TITLE
회원가입 안됨

### ISSUE THREAD

**Issue by navyCarpet** [LubizStudio/dreamseed#3]
고쳐보십쇼

**Comment by Jingzzinbbang** [comment]
어느 단계에서 막히시는지 알 수 있을까요?

**Comment by navyCarpet** [comment]
이메일이 안오는뎁쇼

**Comment by Jingzzinbbang** [comment]
아 앱비밀번호 문제인가 봅니다 빠르게 고치겠습니다

**Comment by Jingzzinbbang** [comment]
수정됨. 또 도메인 [https://testwiki.kr/](https://testwiki.kr/) 변경되었으니 참고바랍니다.
