### ISSUE TITLE
파일 업로드 추가 요청

### ISSUE THREAD

**Issue by NOAH01112** [LubizStudio/dreamseed#6]
기존 imitated seed에서 파일 업로드가 안돼서 너무 불편합니다. 그리고 Blame 기능도 만들어 주실 수 있을까요? 그리고 '이 사용자는 정식 관리자 입니다.' 부분에서 '이 사용자는 정식 관리자입니다' 로 바꾸는게 저는 맞다고 봅니다.

**Comment by MinChoa** [comment]
파일 업로드: 시도는 계속해보고 있으며 언제 성공할지 장담은 못하겠습니다.
Blame: 제 실력 밖의 기능입니다.
정식 관리자 틀: 이거는 굳이 바꿔야 할 이유를 모르겠어서 다른 거 개발하면서 생각나면 수정하겠습니다

**Comment by NOAH01112** [comment]
확인했습니다.
