### ISSUE TITLE
IPv6 차단 가능하게 변경 요청

### ISSUE THREAD

**Issue by NOAH01112** [LubizStudio/dreamseed#7]
기존 imitated seed에서 ipv6이 차단되지 않아서 통피를 차단하기 힘든데 ipv6이 차단되게 만들어주시면 좋겠습니다.

**Comment by MinChoa** [comment]
제가 개발 가능한 난이도가 아닙니다. 잘못 개발했다가는 위험한 오류가 발생할 수도 있구요
